=== rudraraj100/BridgeLabz-Training/java-iostreams-practice/gcr-codebase/iostream-concept-practice/src/main/resources/student_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["name", "age", "email"],
  "properties": {
    "name": { "type": "string" },
    "age": { "type": "integer" },
    "email": { "type": "string", "format": "email" },
    "subjects": { "type": "array", "items": { "type": "string" } }
  }
}

=== rudraraj100/BridgeLabz-Training/java-iostreams-practice/gcr-codebase/iostream-concept-practice/src/main/resources/student_merged.json
[ {
  "name" : "Rudresh Sharma",
  "age" : 21,
  "email" : "rudresh@example.com",
  "subjects" : [ "Math", "Physics" ]
}, {
  "name" : "Anita Verma",
  "age" : 22,
  "email" : "anita@example.com",
  "subjects" : [ "Biology", "Chemistry" ]
}, {
  "name" : "Rahul Singh",
  "age" : 23,
  "email" : "rahul@example.com",
  "subjects" : [ "History", "Geography" ]
} ]
